#################### ROUND 1: reference (W) vs mohithra (B): game 1 ####################
##### game start! #####
INPUT for mohithra:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 717, in <module>
    bot = Bot(player_game, playerColor)
  File "homework.py", line 258, in __init__
    cal_depth  = self.get_calibrated(self.game.remaining_time)
  File "homework.py", line 266, in get_calibrated
    f = open("calibrate.txt","r")
FileNotFoundError: [Errno 2] No such file or directory: 'calibrate.txt'
##### End of output of failed program #####
##### mohithra plays [No Move] in 0.316409111022949s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Game server reported error. Assuming bogus move.
##### GAME OVER: mohithra loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 1 GAMESCORE AFTER GAME 1: reference=1 and mohithra=0 ##########
#################### ROUND 1: reference (B) vs mohithra (W): game 2 ####################
##### game start! #####
INPUT for reference:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" /usr/lib/jvm/jdk-14.0.1/bin/java homework > stulog.txt 2>&1 on reference #####
##### SUCCESS: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" /usr/lib/jvm/jdk-14.0.1/bin/java homework > stulog.txt 2>&1 on reference #####
##### reference plays [E h6 g5] in 0.31s #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Move is valid
Couldn't read file 'current_ply.txt'
Couldn't read content from file 'current_ply.txt'
Couldn't read file 'lastmatchange_ply.txt'
Couldn't read content from file 'lastmatchange_ply.txt'
##### SUCCESS: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
INPUT for mohithra:
GAME
WHITE
300
.b.b.b.b
b.b.b.b.
.b.b.b..
......b.
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 717, in <module>
    bot = Bot(player_game, playerColor)
  File "homework.py", line 258, in __init__
    cal_depth  = self.get_calibrated(self.game.remaining_time)
  File "homework.py", line 266, in get_calibrated
    f = open("calibrate.txt","r")
FileNotFoundError: [Errno 2] No such file or directory: 'calibrate.txt'
##### End of output of failed program #####
##### mohithra plays [No Move] in 0.427742004394531s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Game server reported error. Assuming bogus move.
##### GAME OVER: mohithra loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 1 GAMESCORE AFTER GAME 2: reference=2 and mohithra=0 ##########
#################### ROUND 1: reference (W) vs mohithra (B): game 3 ####################
##### game start! #####
INPUT for mohithra:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 717, in <module>
    bot = Bot(player_game, playerColor)
  File "homework.py", line 258, in __init__
    cal_depth  = self.get_calibrated(self.game.remaining_time)
  File "homework.py", line 266, in get_calibrated
    f = open("calibrate.txt","r")
FileNotFoundError: [Errno 2] No such file or directory: 'calibrate.txt'
##### End of output of failed program #####
##### mohithra plays [No Move] in 0.418951034545898s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Game server reported error. Assuming bogus move.
##### GAME OVER: mohithra loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 1 GAMESCORE AFTER GAME 3: reference=3 and mohithra=0 ##########
#################### ROUND 1: reference (B) vs mohithra (W): game 4 ####################
##### game start! #####
INPUT for reference:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" /usr/lib/jvm/jdk-14.0.1/bin/java homework > stulog.txt 2>&1 on reference #####
##### SUCCESS: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" /usr/lib/jvm/jdk-14.0.1/bin/java homework > stulog.txt 2>&1 on reference #####
##### reference plays [E h6 g5] in 0.31s #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Move is valid
Couldn't read file 'current_ply.txt'
Couldn't read content from file 'current_ply.txt'
Couldn't read file 'lastmatchange_ply.txt'
Couldn't read content from file 'lastmatchange_ply.txt'
##### SUCCESS: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
INPUT for mohithra:
GAME
WHITE
300
.b.b.b.b
b.b.b.b.
.b.b.b..
......b.
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 717, in <module>
    bot = Bot(player_game, playerColor)
  File "homework.py", line 258, in __init__
    cal_depth  = self.get_calibrated(self.game.remaining_time)
  File "homework.py", line 266, in get_calibrated
    f = open("calibrate.txt","r")
FileNotFoundError: [Errno 2] No such file or directory: 'calibrate.txt'
##### End of output of failed program #####
##### mohithra plays [No Move] in 0.418554067611694s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Game server reported error. Assuming bogus move.
##### GAME OVER: mohithra loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 1 GAMESCORE AFTER GAME 4: reference=4 and mohithra=0 ##########
#################### ROUND 1: reference (W) vs mohithra (B): game 5 ####################
##### game start! #####
INPUT for mohithra:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 717, in <module>
    bot = Bot(player_game, playerColor)
  File "homework.py", line 258, in __init__
    cal_depth  = self.get_calibrated(self.game.remaining_time)
  File "homework.py", line 266, in get_calibrated
    f = open("calibrate.txt","r")
FileNotFoundError: [Errno 2] No such file or directory: 'calibrate.txt'
##### End of output of failed program #####
##### mohithra plays [No Move] in 0.343042135238647s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Game server reported error. Assuming bogus move.
##### GAME OVER: mohithra loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 1 GAMESCORE AFTER GAME 5: reference=5 and mohithra=0 ##########
#################### ROUND 1: reference (B) vs mohithra (W): game 6 ####################
##### game start! #####
INPUT for reference:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" /usr/lib/jvm/jdk-14.0.1/bin/java homework > stulog.txt 2>&1 on reference #####
##### SUCCESS: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" /usr/lib/jvm/jdk-14.0.1/bin/java homework > stulog.txt 2>&1 on reference #####
##### reference plays [E b6 c5] in 0.3s #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Move is valid
Couldn't read file 'current_ply.txt'
Couldn't read content from file 'current_ply.txt'
Couldn't read file 'lastmatchange_ply.txt'
Couldn't read content from file 'lastmatchange_ply.txt'
##### SUCCESS: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
INPUT for mohithra:
GAME
WHITE
300
.b.b.b.b
b.b.b.b.
...b.b.b
..b.....
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 717, in <module>
    bot = Bot(player_game, playerColor)
  File "homework.py", line 258, in __init__
    cal_depth  = self.get_calibrated(self.game.remaining_time)
  File "homework.py", line 266, in get_calibrated
    f = open("calibrate.txt","r")
FileNotFoundError: [Errno 2] No such file or directory: 'calibrate.txt'
##### End of output of failed program #####
##### mohithra plays [No Move] in 0.340030193328857s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Game server reported error. Assuming bogus move.
##### GAME OVER: mohithra loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 1 GAMESCORE AFTER GAME 6: reference=6 and mohithra=0 ##########
#################### ROUND 1: reference (W) vs mohithra (B): game 7 ####################
##### game start! #####
INPUT for mohithra:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 717, in <module>
    bot = Bot(player_game, playerColor)
  File "homework.py", line 258, in __init__
    cal_depth  = self.get_calibrated(self.game.remaining_time)
  File "homework.py", line 266, in get_calibrated
    f = open("calibrate.txt","r")
FileNotFoundError: [Errno 2] No such file or directory: 'calibrate.txt'
##### End of output of failed program #####
##### mohithra plays [No Move] in 0.392614126205444s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Game server reported error. Assuming bogus move.
##### GAME OVER: mohithra loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 1 GAMESCORE AFTER GAME 7: reference=7 and mohithra=0 ##########
#################### ROUND 1: reference (B) vs mohithra (W): game 8 ####################
##### game start! #####
INPUT for reference:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" /usr/lib/jvm/jdk-14.0.1/bin/java homework > stulog.txt 2>&1 on reference #####
##### SUCCESS: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" /usr/lib/jvm/jdk-14.0.1/bin/java homework > stulog.txt 2>&1 on reference #####
##### reference plays [E b6 c5] in 0.32s #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Move is valid
Couldn't read file 'current_ply.txt'
Couldn't read content from file 'current_ply.txt'
Couldn't read file 'lastmatchange_ply.txt'
Couldn't read content from file 'lastmatchange_ply.txt'
##### SUCCESS: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
INPUT for mohithra:
GAME
WHITE
300
.b.b.b.b
b.b.b.b.
...b.b.b
..b.....
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 717, in <module>
    bot = Bot(player_game, playerColor)
  File "homework.py", line 258, in __init__
    cal_depth  = self.get_calibrated(self.game.remaining_time)
  File "homework.py", line 266, in get_calibrated
    f = open("calibrate.txt","r")
FileNotFoundError: [Errno 2] No such file or directory: 'calibrate.txt'
##### End of output of failed program #####
##### mohithra plays [No Move] in 0.327919006347656s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Game server reported error. Assuming bogus move.
##### GAME OVER: mohithra loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 1 GAMESCORE AFTER GAME 8: reference=8 and mohithra=0 ##########
#################### ROUND 1: reference (W) vs mohithra (B): game 9 ####################
##### game start! #####
INPUT for mohithra:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_1_reference_mohithra.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on mohithra #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 717, in <module>
    bot = Bot(player_game, playerColor)
  File "homework.py", line 258, in __init__
    cal_depth  = self.get_calibrated(self.game.remaining_time)
  File "homework.py", line 266, in get_calibrated
    f = open("calibrate.txt","r")
FileNotFoundError: [Errno 2] No such file or directory: 'calibrate.txt'
##### End of output of failed program #####
##### mohithra plays [No Move] in 0.45724081993103s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_1_reference_mohithra #####
Game server reported error. Assuming bogus move.
##### GAME OVER: mohithra loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 1 GAMESCORE AFTER GAME 9: reference=9 and mohithra=0 ##########


########## GRAND WINNER ROUND 1 IS reference BY 9 vs 0 GAMESCORE ##########
